# =============================================================================
# A_MM_03_merge_vdem.R
# Purpose: Join V-Dem v14 country-year indices to the MM panel. Outcomes
#          needed by A_MM:
#            v2x_polyarchy       (electoral democracy index)
#            v2x_libdem          (liberal democracy index)
#            v2x_partipdem       (participatory democracy index)
#            v2xel_frefair       (clean elections)
#            v2x_frassoc_thick   (freedom of association)
#            v2x_freexp_altinf   (freedom of expression)
#            v2xca_academ        (academic & cultural freedom)
#          Join key: country -> V-Dem country_name (via `countrycode`).
# Inputs:
#   data/intermediate/mm_country_year.rds
#   V-Dem v14 via `vdemdata::vdem`  (TODO: if not installed, read CSV export)
# Outputs:
#   data/intermediate/mm_vdem.rds
#   output/tables/mm_vdem_macros.tex
# =============================================================================

suppressPackageStartupMessages({
  library(here); library(dplyr); library(tidyr); library(readr)
})

log_path <- here("quality_reports", "session_logs",
                 format(Sys.Date(), "%Y-%m-%d_A_MM_03_vdem.log"))
dir.create(dirname(log_path), showWarnings = FALSE, recursive = TRUE)
sink(log_path, split = TRUE)

message("=== A_MM_03 Merge V-Dem ===")
message("Run at: ", format(Sys.time()))

panel <- readRDS(here("data", "intermediate", "mm_country_year.rds"))

vdem_cols <- c("v2x_polyarchy", "v2x_libdem", "v2x_partipdem",
               "v2xel_frefair", "v2x_frassoc_thick", "v2x_freexp_altinf",
               "v2xca_academ")

if (requireNamespace("vdemdata", quietly = TRUE)) {
  vd <- vdemdata::vdem
  # Harmonize country names via countrycode if available.
  if (requireNamespace("countrycode", quietly = TRUE)) {
    panel$iso3c <- countrycode::countrycode(panel$country, "country.name",
                                            "iso3c", warn = FALSE)
    vd$iso3c    <- countrycode::countrycode(vd$country_name, "country.name",
                                            "iso3c", warn = FALSE)
  }
  vd_sel <- vd %>% select(iso3c, year, any_of(vdem_cols))
  out <- left_join(panel, vd_sel, by = c("iso3c", "year"))
  message("  Joined V-Dem via iso3c; rows=", format(nrow(out), big.mark = ","))
} else {
  message("  vdemdata not installed; emitting NA columns.")
  out <- panel
  for (col in vdem_cols) out[[col]] <- NA_real_
}

saveRDS(out, here("data", "intermediate", "mm_vdem.rds"))
message("Saved: data/intermediate/mm_vdem.rds")

macro <- function(name, value) sprintf("\\newcommand{\\%s}{%s}", name, value)
nonmiss <- sapply(vdem_cols, function(c) round(100 * mean(!is.na(out[[c]])), 1))
writeLines(
  c("% Auto-generated by A_MM_03_merge_vdem.R",
    paste0("% Generated: ", Sys.time()),
    macro("MMVdemPctPolyarchy", sprintf("%.1f", nonmiss["v2x_polyarchy"])),
    macro("MMVdemPctLibdem",    sprintf("%.1f", nonmiss["v2x_libdem"]))),
  here("output", "tables", "mm_vdem_macros.tex")
)

sink()
