# =============================================================================
# A_US_08_bjs_imputation.R
# Purpose: Borusyak-Jaravel-Spiess (BJS 2024) efficient imputation estimator
#          as an efficiency-check counterweight to the CS ATT(g,t) headline.
#          Same two-arm nonviolent vs violent treatment definitions as A_US_06.
# Method:
#   - `didimputation::did_imputation()` on binary treatment derived from
#     the 90th-percentile intensity cutoff (see A_US_06).
#   - Pre-treatment horizons reported for parallel-trends sanity check.
#   - Clustered SEs by county.
# Inputs:
#   data/analysis/a_us_panel.rds
# Outputs:
#   data/analysis/a_us_bjs_results.rds
#   output/tables/a_us_bjs_summary.csv
#   output/tables/a_us_bjs_macros.tex
# =============================================================================

suppressPackageStartupMessages({
  library(here); library(dplyr); library(readr)
})

if (!requireNamespace("didimputation", quietly = TRUE)) {
  stop("Install 'didimputation' first.")
}

log_path <- here("quality_reports", "session_logs",
                 format(Sys.Date(), "%Y-%m-%d_A_US_08_bjs.log"))
dir.create(dirname(log_path), showWarnings = FALSE, recursive = TRUE)
sink(log_path, split = TRUE)

message("=== A_US_08 BJS imputation estimator ===")
message("Run at: ", format(Sys.time()))

panel <- readRDS(here("data", "analysis", "a_us_panel.rds")) %>%
  filter(violence_def == "strict") %>%
  arrange(fips_code, year) %>%
  mutate(id = as.integer(as.factor(fips_code)))

# Binary treatment assignment (matches A_US_06 logic).
assign_treat <- function(df, col) {
  cutoff <- quantile(df[[col]][df[[col]] > 0], 0.90, na.rm = TRUE)
  df %>%
    mutate(above = as.integer(.data[[col]] >= cutoff & cutoff > 0)) %>%
    group_by(id) %>%
    mutate(treat_time = ifelse(any(above == 1),
                               min(year[above == 1]),
                               NA_integer_),
           rel_time = year - treat_time,
           treat = as.integer(!is.na(treat_time) & year >= treat_time)) %>%
    ungroup()
}

panel_nv <- assign_treat(panel, "nonviolent_per_cap")
panel_v  <- assign_treat(panel, "violent_per_cap")

outcomes <- c("spend_public_safety", "spend_police", "spend_welfare",
              "mpv_killings")

run_bjs <- function(df, y) {
  if (all(is.na(df[[y]]))) return(NULL)
  tryCatch(
    didimputation::did_imputation(
      data   = df,
      yname  = y,
      gname  = "treat_time",
      tname  = "year",
      idname = "id",
      horizon = TRUE,
      pretrends = -5:-1,
      cluster_var = "id"
    ),
    error = function(e) { message("  BJS failed: ", e$message); NULL }
  )
}

results <- list()
for (y in outcomes) {
  message("  BJS for ", y, " [nv]"); results[[paste0(y, "__nv")]] <- run_bjs(panel_nv, y)
  message("  BJS for ", y, " [v]");  results[[paste0(y, "__v")]]  <- run_bjs(panel_v, y)
}

saveRDS(results, here("data", "analysis", "a_us_bjs_results.rds"))
message("Saved: data/analysis/a_us_bjs_results.rds")

# ---- Macros -------------------------------------------------------------
macro <- function(name, value) sprintf("\\newcommand{\\%s}{%s}", name, value)
writeLines(
  c("% Auto-generated by A_US_08_bjs_imputation.R",
    paste0("% Generated: ", Sys.time()),
    macro("AUSBJSNSpecs", length(results))),
  here("output", "tables", "a_us_bjs_macros.tex")
)

sink()
