# =============================================================================
# A_US_07_dcdh_continuous.R
# Purpose: de Chaisemartin-D'Haultfœuille (dCdH) continuous-dose DiD on the
#          A_US panel, where the treatment is the *intensity* of
#          nonviolent / violent participation per capita rather than a
#          binary flag. Complements the CS ATT(g,t) estimates in A_US_06.
# Method:
#   - `DIDmultiplegtDYN::did_multiplegt_dyn()` with a continuous treatment
#     column. Run separately for nonviolent and violent arms.
#   - effect_horizons = 0:4; placebo_horizons = 1:3.
#   - Clustered SEs by county; bootstrap = TRUE where sample allows.
#   - Primary outcome: spend_public_safety. Secondary stack mirrors A_US_06.
# Inputs:
#   data/analysis/a_us_panel.rds
# Outputs:
#   data/analysis/a_us_dcdh_results.rds
#   output/figures/a_us_dcdh_event_study.pdf
#   output/tables/a_us_dcdh_summary.csv
#   output/tables/a_us_dcdh_macros.tex
# =============================================================================

suppressPackageStartupMessages({
  library(here); library(dplyr); library(readr)
  library(ggplot2); library(ggthemes)
})

if (!requireNamespace("DIDmultiplegtDYN", quietly = TRUE)) {
  stop("Install 'DIDmultiplegtDYN' first.")
}
# DIDmultiplegtDYN uses polars under the hood; the package must be
# attached (not just available) or the estimator fails with
# "Evaluation failed in $with_columns()".
if (requireNamespace("polars", quietly = TRUE)) {
  suppressPackageStartupMessages(library(polars))
} else {
  message("  polars not installed; did_multiplegt_dyn may fail.")
}

log_path <- here("quality_reports", "session_logs",
                 format(Sys.Date(), "%Y-%m-%d_A_US_07_dcdh.log"))
dir.create(dirname(log_path), showWarnings = FALSE, recursive = TRUE)
sink(log_path, split = TRUE)

message("=== A_US_07 dCdH continuous-dose DiD ===")
message("Run at: ", format(Sys.time()))

panel <- readRDS(here("data", "analysis", "a_us_panel.rds")) %>%
  filter(violence_def == "strict") %>%
  arrange(fips_code, year) %>%
  mutate(id = as.integer(as.factor(fips_code)))

outcomes <- c("spend_public_safety", "spend_police", "spend_welfare",
              "spend_education", "spend_highways", "mpv_killings")

run_dcdh <- function(df, y, d) {
  if (all(is.na(df[[y]]))) return(NULL)
  tryCatch(
    DIDmultiplegtDYN::did_multiplegt_dyn(
      df                = df,
      outcome           = y,
      group             = "id",
      time              = "year",
      treatment         = d,
      effects           = 5,
      placebo           = 3,
      cluster           = "id",
      graph_off         = TRUE
    ),
    error = function(e) { message("  dCdH failed: ", e$message); NULL }
  )
}

# Wrap each run in list() so NULL slots are retained (assigning NULL to a
# list element deletes it, which is what produced AUSDCDHNSpecs = 0).
results <- list()
for (y in outcomes) {
  message("  Running dCdH for: ", y)
  results[[paste0(y, "__nv")]] <- list(obj = run_dcdh(panel, y, "nonviolent_per_cap"))
  results[[paste0(y, "__v")]]  <- list(obj = run_dcdh(panel, y, "violent_per_cap"))
}

# ---- Save ---------------------------------------------------------------
dir.create(here("data", "analysis"), showWarnings = FALSE, recursive = TRUE)
saveRDS(results, here("data", "analysis", "a_us_dcdh_results.rds"))
message("Saved: data/analysis/a_us_dcdh_results.rds")

# ---- Summary + macros ---------------------------------------------------
n_success <- sum(!vapply(results,
                         function(r) is.null(r$obj), logical(1)))
# Extract the average-ATT effect per run (DIDmultiplegtDYN returns the
# dynamic effects in results$Effects and/or results$effects).
extract_avg <- function(r) {
  if (is.null(r$obj)) return(tibble(att = NA_real_, se = NA_real_))
  eff <- tryCatch({
    e <- r$obj
    # Try common return slots; fall back to NA if structure differs.
    if (is.list(e) && !is.null(e$results) && is.list(e$results)) {
      eff_tbl <- e$results$Effects
    } else eff_tbl <- NULL
    eff_tbl
  }, error = function(e) NULL)
  if (is.null(eff)) return(tibble(att = NA_real_, se = NA_real_))
  tibble(att = suppressWarnings(mean(eff[, "Estimate"], na.rm = TRUE)),
         se  = suppressWarnings(mean(eff[, "SE"],       na.rm = TRUE)))
}
eff_summary <- bind_rows(lapply(results, extract_avg), .id = "key")
write_csv(eff_summary, here("output", "tables", "a_us_dcdh_summary.csv"))

macro <- function(name, value) sprintf("\\newcommand{\\%s}{%s}", name, value)
writeLines(
  c("% Auto-generated by A_US_07_dcdh_continuous.R",
    paste0("% Generated: ", Sys.time()),
    macro("AUSDCDHNSpecs", n_success),
    macro("AUSDCDHNAttempted", length(results))),
  here("output", "tables", "a_us_dcdh_macros.tex")
)

sink()
