# =============================================================================
# A_US_12_paper_assets.R
# Purpose: Consolidate every figure, table and macro needed by the A_US
#          Nonviolence Premium manuscript. Concatenates all per-step macro
#          files into a single `paper/A_nonviolence_premium_us/statistics.tex`
#          that the .tex master \input{}s.
#
#          Also copies / symlinks every PDF figure required by the paper into
#          `paper/A_nonviolence_premium_us/figures/` so that the LaTeX build
#          is self-contained.
# Inputs:
#   output/tables/ccc_audit_macros.tex
#   output/tables/ccc_imputation_macros.tex
#   output/tables/ccc_panel_macros.tex
#   output/tables/a_us_outcome_macros.tex
#   output/tables/a_us_descriptives_macros.tex
#   output/tables/a_us_cs_macros.tex
#   output/tables/a_us_dcdh_macros.tex
#   output/tables/a_us_bjs_macros.tex
#   output/tables/a_us_honestdid_macros.tex
#   output/tables/a_us_het_macros.tex
#   output/tables/a_us_multiverse_macros.tex
# Outputs:
#   paper/A_nonviolence_premium_us/statistics.tex
#   paper/A_nonviolence_premium_us/figures/*.pdf (copies)
# =============================================================================

suppressPackageStartupMessages({
  library(here)
})

log_path <- here("quality_reports", "session_logs",
                 format(Sys.Date(), "%Y-%m-%d_A_US_12_paper.log"))
dir.create(dirname(log_path), showWarnings = FALSE, recursive = TRUE)
sink(log_path, split = TRUE)

message("=== A_US_12 Paper asset consolidation ===")
message("Run at: ", format(Sys.time()))

paper_dir <- here("paper", "A_nonviolence_premium_us")
fig_out   <- file.path(paper_dir, "figures")
dir.create(paper_dir, showWarnings = FALSE, recursive = TRUE)
dir.create(fig_out,   showWarnings = FALSE, recursive = TRUE)

# ---- Concatenate macro files --------------------------------------------
macro_order <- c(
  "ccc_audit_macros.tex",
  "ccc_imputation_macros.tex",
  "ccc_panel_macros.tex",
  "a_us_outcome_macros.tex",
  "a_us_descriptives_macros.tex",
  "a_us_cs_macros.tex",
  "a_us_dcdh_macros.tex",
  "a_us_bjs_macros.tex",
  "a_us_honestdid_macros.tex",
  "a_us_het_macros.tex",
  "a_us_multiverse_macros.tex"
)

stats_lines <- c(
  "% =========================================================================",
  "% statistics.tex  -- Auto-generated by R/A_US_12_paper_assets.R",
  paste0("% Generated: ", Sys.time()),
  "% Concatenates per-step macro files from output/tables/.",
  "% =========================================================================",
  ""
)

# LaTeX control sequences may contain only letters; some upstream scripts
# emitted macro names ending in digits (e.g. \CCCImpPctT1). Rewrite any
# embedded digits inside the \newcommand name to their spelled-out
# equivalents before writing statistics.tex. Values (inside the second
# pair of braces) are left untouched.
digit_words <- c(`0` = "Zero", `1` = "One", `2` = "Two", `3` = "Three",
                 `4` = "Four", `5` = "Five", `6` = "Six", `7` = "Seven",
                 `8` = "Eight", `9` = "Nine")
spell_digits <- function(name) {
  out <- name
  for (d in names(digit_words)) {
    out <- gsub(d, digit_words[[d]], out, fixed = TRUE)
  }
  out
}
sanitize_macro_names <- function(lines) {
  pattern <- "^(\\s*\\\\newcommand\\{\\\\)([A-Za-z0-9]+)(\\}.*)$"
  has_match <- grepl(pattern, lines, perl = TRUE)
  out <- lines
  idx <- which(has_match)
  for (i in idx) {
    m <- regmatches(lines[i], regexec(pattern, lines[i], perl = TRUE))[[1]]
    if (length(m) < 4) next
    name <- m[3]
    if (!grepl("[0-9]", name)) next
    out[i] <- paste0(m[2], spell_digits(name), m[4])
  }
  out
}

for (f in macro_order) {
  p <- here("output", "tables", f)
  if (file.exists(p)) {
    raw <- readLines(p)
    clean <- sanitize_macro_names(raw)
    stats_lines <- c(stats_lines,
                     paste0("% --- ", f, " ---"),
                     clean,
                     "")
    message("  + ", f)
  } else {
    stats_lines <- c(stats_lines,
                     paste0("% --- ", f, " (missing; run upstream script) ---"),
                     "")
    message("  [missing] ", f)
  }
}

writeLines(stats_lines, file.path(paper_dir, "statistics.tex"))
message("Wrote: paper/A_nonviolence_premium_us/statistics.tex")

# ---- Copy figures -------------------------------------------------------
figs <- c(
  "a_us_timeseries.pdf",
  "a_us_choropleth.pdf",
  "a_us_intensity_dist.pdf",
  "a_us_cs_event_study.pdf",
  "a_us_honestdid_publicsafety.pdf",
  "a_us_het_era.pdf",
  "a_us_multiverse.pdf"
)

for (f in figs) {
  src <- here("output", "figures", f)
  dst <- file.path(fig_out, f)
  if (file.exists(src)) {
    file.copy(src, dst, overwrite = TRUE)
    message("  copied ", f)
  } else {
    message("  [missing fig] ", f)
  }
}

message("\nPaper assets ready at: ", paper_dir)
sink()
